# Generated by Django 4.2.7 on 2026-03-25 17:24

from django.db import migrations, models
import time


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.FloatField(default=time.time)),
                ('end_time', models.FloatField(default=time.time)),
                ('src_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('dst_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('sport', models.IntegerField(blank=True, null=True)),
                ('dport', models.IntegerField(blank=True, null=True)),
                ('protocol', models.CharField(blank=True, max_length=10)),
                ('bytes_fwd', models.BigIntegerField(default=0)),
                ('bytes_bwd', models.BigIntegerField(default=0)),
                ('packets_fwd', models.IntegerField(default=0)),
                ('packets_bwd', models.IntegerField(default=0)),
                ('flow_duration', models.FloatField(default=0.0)),
                ('attack_type', models.CharField(blank=True, max_length=64)),
                ('severity', models.CharField(blank=True, max_length=16)),
                ('confidence', models.FloatField(default=0.0)),
                ('is_simulated', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['start_time'], name='model_app_n_start_t_f2d7c1_idx'), models.Index(fields=['attack_type'], name='model_app_n_attack__1f74e6_idx'), models.Index(fields=['severity'], name='model_app_n_severit_24a18c_idx'), models.Index(fields=['src_ip'], name='model_app_n_src_ip_93a6f5_idx')],
            },
        ),
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(unique=True)),
                ('reason', models.TextField(blank=True)),
                ('blocked_at', models.FloatField(default=time.time)),
                ('blocked_by', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('unblocked_at', models.FloatField(blank=True, null=True)),
                ('unblocked_by', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-blocked_at'],
                'indexes': [models.Index(fields=['ip'], name='model_app_b_ip_ffa168_idx'), models.Index(fields=['is_active'], name='model_app_b_is_acti_402150_idx')],
            },
        ),
        migrations.CreateModel(
            name='AlertRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.FloatField(default=time.time)),
                ('src_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('dst_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('sport', models.IntegerField(blank=True, null=True)),
                ('dport', models.IntegerField(blank=True, null=True)),
                ('protocol', models.CharField(blank=True, max_length=10)),
                ('attack_type', models.CharField(blank=True, max_length=64)),
                ('severity', models.CharField(blank=True, max_length=16)),
                ('confidence', models.FloatField(default=0.0)),
                ('mitre_id', models.CharField(blank=True, max_length=32)),
                ('mitre_tactic', models.CharField(blank=True, max_length=64)),
                ('abuse_score', models.IntegerField(default=0)),
                ('incident_id', models.CharField(blank=True, max_length=64)),
                ('is_simulated', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='model_app_a_timesta_d537c9_idx'), models.Index(fields=['src_ip'], name='model_app_a_src_ip_21c5d6_idx'), models.Index(fields=['attack_type'], name='model_app_a_attack__31171c_idx')],
            },
        ),
    ]
